from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

from PIL import Image

from ..adapters.openpencil import build_fig
from ..schema import validate_data
from ..util import load_data, resolve_relative, sha256_file, stable_id, write_json
from .assets import build_asset_contact_sheet, build_assets
from .layout import from_inline, from_layout_authority, style_for
from .preview import build_overlay
from .text_fallback import build_text_fallbacks


def _prepare_reference(job: dict[str, Any], job_dir: Path, output_root: Path) -> tuple[Path, str]:
    source = resolve_relative(job_dir, job["reference"]["path"])
    if not source.is_file():
        raise FileNotFoundError(f"Reference image not found: {source}")
    source_dir = output_root / "Source"
    source_dir.mkdir(parents=True, exist_ok=True)
    original = source_dir / f"reference-original{source.suffix.lower() or '.png'}"
    shutil.copy2(source, original)

    normalized = source_dir / "reference.png"
    with Image.open(source) as image:
        image = image.convert("RGBA")
        screen_box = job["reference"].get("screenBox")
        if screen_box:
            x, y, width, height = screen_box
            image = image.crop((x, y, x + width, y + height))
        image.save(normalized)
    return normalized, sha256_file(original)


def _write_readme(output_root: Path, job: dict[str, Any], openpencil_built: bool, asset_count: int) -> None:
    fig_line = "- `Design/*.fig`: OpenPencil editable design source\n" if openpencil_built else ""
    completeness_line = "- `Reports/OpenPencil/fig-completeness.json`: five-page structural completion gate\n" if openpencil_built else ""
    asset_line = "- `Previews/assets-checkerboard.png`: transparency and component-boundary review\n" if asset_count else ""
    content = f"""# {job.get('name', job['id'])}

Generated by UI Rebuilder from a consumer-owned reconstruction job.

## Canonical files

- `uiir.json`: semantic hierarchy and parent-relative layout
- `asset-manifest.json`: raster asset provenance, scaling and hashes
- `Source/`: immutable input snapshots used by this run
- `Previews/layout-overlay.png`: geometry review overlay
{asset_line}- `Reports/build.json`: reproducibility and adapter results
{fig_line}{completeness_line}
The package is a draft until a human approves hierarchy, typography, assets and visual difference.
"""
    (output_root / "README.md").write_text(content, encoding="utf-8")


def _apply_node_overrides(nodes: list[dict[str, Any]], overrides: dict[str, Any]) -> None:
    by_name = {node["name"]: node for node in nodes}
    for name, override in overrides.items():
        node = by_name.get(name)
        if node is None:
            raise ValueError(f"nodeOverrides targets an unknown node: {name}")
        for key, value in override.items():
            if key in {"style", "layout"}:
                node[key] = {**node.get(key, {}), **value}
            else:
                node[key] = value


def _append_extra_nodes(nodes: list[dict[str, Any]], specs: list[dict[str, Any]], style: dict[str, Any]) -> None:
    by_name = {node["name"]: node for node in nodes}
    used_ids = {node["id"] for node in nodes}
    for spec in specs:
        name = spec["name"]
        if name in by_name:
            raise ValueError(f"extraNodes duplicates an existing node name: {name}")
        parent_name = spec.get("parent")
        parent = by_name.get(parent_name) if parent_name else None
        if parent_name and parent is None:
            raise ValueError(f"extraNodes parent must be declared before its child: {name} -> {parent_name}")
        node_id = spec.get("id") or stable_id(name)
        if node_id in used_ids:
            raise ValueError(f"extraNodes duplicates an existing node id: {node_id}")
        bounds = [float(value) for value in spec["bounds"]]
        if parent:
            parent_abs = parent["absoluteBounds"]
            absolute = [parent_abs[0] + bounds[0], parent_abs[1] + bounds[1], bounds[2], bounds[3]]
        else:
            absolute = bounds.copy()
        node_type = spec["type"]
        node: dict[str, Any] = {
            "id": node_id,
            "name": name,
            "type": node_type,
            "parent": parent["id"] if parent else None,
            "bounds": bounds,
            "absoluteBounds": absolute,
            "role": spec.get("role", "synthetic-semantic-node"),
            "dynamic": bool(spec.get("dynamic", node_type == "text")),
            "layout": {"mode": spec.get("layoutMode", "NONE"), "positioning": spec.get("layoutPositioning", "AUTO")},
            "style": {**style_for(name, node_type, style), **spec.get("style", {})},
            "asset": None,
            "provenance": {
                "method": "manual",
                "confidence": float(spec.get("confidence", 1.0)),
                "reviewRequired": bool(spec.get("reviewRequired", False)),
                "reason": "consumer-declared extraNode",
            },
        }
        if node_type == "text":
            node["text"] = spec.get("text", name.rsplit("/", 1)[-1])
        nodes.append(node)
        by_name[name] = node
        used_ids.add(node_id)


def build_package(
    job_path: Path,
    output_override: Path | None = None,
    *,
    style_override: Path | None = None,
    build_context: dict[str, str] | None = None,
    force: bool = False,
    skip_openpencil: bool = False,
    openpencil_repo: Path | None = None,
    export_openpencil_preview: bool = True,
) -> dict[str, Any]:
    job_path = job_path.resolve()
    job_dir = job_path.parent
    job = load_data(job_path)
    validate_data("reconstruction-job", job)
    style_path = style_override.resolve() if style_override is not None else resolve_relative(job_dir, job["styleProfile"])
    style = load_data(style_path)
    validate_data("style-profile", style)

    if output_override is not None:
        output_root = output_override.expanduser().resolve()
    elif job.get("output"):
        output_root = resolve_relative(job_dir, str(job["output"]))
    else:
        raise ValueError("Output directory is required: pass --output or set job.output")
    if output_root.exists() and any(output_root.iterdir()) and not force:
        raise FileExistsError(f"Output directory is not empty; pass --force to update it: {output_root}")
    output_root.mkdir(parents=True, exist_ok=True)
    write_json(
        output_root / "Reports" / "build-state.json",
        {"status": "building", "job": str(job_path), "output": str(output_root)},
    )

    reference, original_hash = _prepare_reference(job, job_dir, output_root)
    layout = job["layout"]
    if layout["kind"] == "layout-authority":
        layout_path = resolve_relative(job_dir, layout["path"])
        resolution, nodes = from_layout_authority(
            layout_path,
            style,
            screen_node=layout.get("screenNode"),
            text_overrides=job.get("textOverrides"),
        )
        layout_source = str(layout_path)
    else:
        resolution, nodes = from_inline(layout, style)
        layout_source = "inline"
    _append_extra_nodes(nodes, job.get("extraNodes", []), style)
    _apply_node_overrides(nodes, job.get("nodeOverrides", {}))

    source_snapshot = output_root / "Source" / "reference.png"
    with Image.open(source_snapshot) as image:
        if image.size != tuple(resolution):
            image.convert("RGBA").resize(tuple(resolution), Image.Resampling.LANCZOS).save(source_snapshot)

    style_snapshot = output_root / "Source" / "style-profile.json"
    job_snapshot = output_root / "Source" / "job.json"
    write_json(style_snapshot, style)
    write_json(job_snapshot, job)
    manifest = build_assets(job, job_dir, source_snapshot, output_root, resolution)
    validate_data("asset-manifest", manifest)
    write_json(output_root / "asset-manifest.json", manifest)
    nodes_by_name = {node["name"]: node for node in nodes}
    for asset in manifest["assets"]:
        target_names = asset.get("targetNodes") or ([asset["targetNode"]] if asset.get("targetNode") else [])
        for target_name in target_names:
            target = nodes_by_name.get(target_name)
            if target is None:
                raise ValueError(f"Asset {asset['id']} targets an unknown UIIR node: {target_name}")
            if target.get("asset"):
                raise ValueError(f"Multiple assets target UIIR node: {target_name}")
            target["asset"] = {
                "id": asset["id"],
                "path": asset["output"],
                "scaling": asset["scaling"],
                "opacity": asset.get("opacity", 1.0),
                "alpha": asset.get("alpha"),
            }
    uiir = {
        "schemaVersion": 1,
        "id": job["id"],
        "name": job.get("name", job["id"]),
        "referenceResolution": resolution,
        "source": {
            "path": "Source/reference.png",
            "sha256": sha256_file(source_snapshot),
            "originalSha256": original_hash,
        },
        "styleProfile": {
            "id": style["id"],
            "sha256": sha256_file(style_snapshot),
            "status": style["status"],
        },
        "pages": [{"id": "20-visual", "name": "20_Visual", "nodes": nodes}],
        "metadata": {
            "job": str(job_path),
            "layoutSource": layout_source,
            **({"workspace": build_context} if build_context else {}),
        },
    }
    text_fallback_report = build_text_fallbacks(job, job_dir, uiir, output_root)
    validate_data("uiir", uiir)
    write_json(output_root / "uiir.json", uiir)
    asset_preview = build_asset_contact_sheet(manifest, output_root)
    build_overlay(source_snapshot, nodes, output_root / "Previews" / "layout-overlay.png", tuple(resolution))

    requested = set(job.get("outputs", ["package"]))
    openpencil_report: dict[str, Any] | None = None
    if "openpencil-fig" in requested and not skip_openpencil:
        openpencil_report = build_fig(
            uiir,
            style,
            output_root,
            explicit_repo=openpencil_repo,
            export_preview=export_openpencil_preview,
        )
    _write_readme(output_root, job, openpencil_report is not None, len(manifest["assets"]))
    report = {
        "schemaVersion": 1,
        "job": str(job_path),
        "output": str(output_root),
        "uiir": "uiir.json",
        "manifest": "asset-manifest.json",
        "nodeCount": len(nodes),
        "assetCount": len(manifest["assets"]),
        "textFallbackCount": text_fallback_report["count"],
        "textFallback": text_fallback_report,
        "assetPreview": asset_preview.relative_to(output_root).as_posix() if asset_preview else None,
        "openpencil": openpencil_report,
        "status": "complete-fig-pending-visual-approval" if openpencil_report else "built-pending-visual-approval",
        **({"context": build_context} if build_context else {}),
    }
    write_json(output_root / "Reports" / "build.json", report)
    write_json(
        output_root / "Reports" / "build-state.json",
        {"status": "complete", "job": str(job_path), "output": str(output_root)},
    )
    return report
